  version: '2'

volumes:
  client_data:
  node_data:

services:
  baker:
    image: tezos/tezos:latest
    hostname: baker-004-Pt24m4xi
    environment:
      - PROTOCOL=004-Pt24m4xi
    command: tezos-baker
    links:
      - node
    volumes:
      - node_data:/var/run/tezos/node:ro
      - client_data:/var/run/tezos/client
    restart: on-failure

  endorser:
    image: tezos/tezos:latest
    hostname: endorser-004-Pt24m4xi
    environment:
      - PROTOCOL=004-Pt24m4xi
    command: tezos-endorser
    links:
      - node
    volumes:
      - client_data:/var/run/tezos/client
    restart: on-failure
