name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ github.repository }}
      #tezosfullnode:$(date +%s)
    
    - name: Push
      run: |
        docker tag ${{ github.repository }}:latest afielologisele/tezosfullnode:latest
        docker push afielologisele/tezosfullnode:latest
